services:
  # Backend service
  - type: web
    name: e-nagarpalika-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production

  # Frontend service
  - type: web
    name: e-nagarpalika-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://e-nagarpalika-backend.onrender.com
      - key: NODE_ENV
        value: production 