services:
  # Backend Service
  - type: web
    name: e-nagarpalika-backend
    env: node
    rootDir: e-nagarpalika-backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend Service
  - type: static
    name: e-nagarpalika-frontend
    rootDir: e-nagarpalika-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_NODE_ENV
        value: production 